import { useLocale } from "@/lib/i18n/locale-provider";
import { useDialogFocus } from "@/lib/use-dialog-focus";
import { X } from "@phosphor-icons/react";
import type { EventCategory } from "@/data/mock-events";
import type { EventFilters, TimeFilter } from "@/lib/events/filters";
import { AppIconButton } from "@/components/ui/app-icon-button";

const categories: Array<EventCategory | "Tutte"> = ["Tutte","Aperitivo","Musica live","Club","Food","Outdoor","Cultura","Bar","Elettronica"];

export function FilterSheet({ value, resultCount, onChange, onReset, onClose }: { value: EventFilters; resultCount: number; onChange: (value: EventFilters) => void; onReset: () => void; onClose: () => void }) {
  const { t } = useLocale();
  const dialog = useDialogFocus(onClose);
  const update = (partial: Partial<EventFilters>) => onChange({ ...value, ...partial });
  return <div ref={dialog} className="sheet-backdrop" role="presentation" onMouseDown={(event) => event.currentTarget === event.target && onClose()}><section className="filter-sheet" role="dialog" aria-modal="true" aria-labelledby="filters-title"><header><div><p>{t("Esplora meglio")}</p><h1 id="filters-title">{t("Filtri")}</h1></div><AppIconButton icon={X} label={t("Chiudi filtri")} onClick={onClose} /></header><div className="filter-group"><h2>{t("Quando")}</h2><div className="choice-row">{([['all','Tutto'],['tonight','Stasera'],['tomorrow','Domani'],['weekend','Weekend']] as Array<[TimeFilter,string]>).map(([id,label]) => <button type="button" key={id} aria-pressed={value.time === id} className={value.time === id ? "is-active" : ""} onClick={() => update({time:id})}>{t(label)}</button>)}</div></div><div className="filter-group"><h2>{t("Distanza")} <span>{t("entro")} {value.maxDistance} km</span></h2><input type="range" min="1" max="20" step="1" value={value.maxDistance} onChange={(event) => update({maxDistance:Number(event.target.value)})} aria-label={t("Distanza massima")} /></div><div className="filter-group"><h2>{t("Categoria")}</h2><div className="choice-row choice-row--wrap">{categories.map((category) => <button type="button" key={category} aria-pressed={value.category === category} className={value.category === category ? "is-active" : ""} onClick={() => update({category})}>{t(category)}</button>)}</div></div><div className="filter-group"><h2>{t("Prezzo")}</h2><div className="choice-row"><button type="button" className={value.maxPrice === null ? "is-active" : ""} onClick={() => update({maxPrice:null})}>{t("Qualsiasi")}</button><button type="button" className={value.maxPrice === 0 ? "is-active" : ""} onClick={() => update({maxPrice:0})}>{t("Gratis")}</button><button type="button" className={value.maxPrice === 15 ? "is-active" : ""} onClick={() => update({maxPrice:15})}>{t("Fino a 15 €")}</button></div></div><footer><button type="button" className="reset-button" onClick={onReset}>Reset</button><button type="button" className="primary-cta" onClick={onClose}>{t("Mostra")} {resultCount} {t("eventi")}</button></footer></section></div>;
}
